# Generated by Django 3.2.18 on 2023-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='featured_links/')),
                ('first_image_position', models.CharField(default='unset', max_length=100)),
                ('second_image', models.ImageField(upload_to='featured_links/')),
                ('second_image_position', models.CharField(default='unset', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='index_upcoming_events_images/')),
                ('first_image_position', models.CharField(default='unset', max_length=100)),
                ('second_image', models.ImageField(upload_to='index_upcoming_events_images/')),
                ('second_image_position', models.CharField(default='unset', max_length=100)),
            ],
        ),
    ]
