# Generated by Django 3.2.18 on 2023-07-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_featuredlinks_upcomingevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedLinks',
        ),
        migrations.RemoveField(
            model_name='upcomingevent',
            name='first_image_position',
        ),
        migrations.RemoveField(
            model_name='upcomingevent',
            name='second_image_position',
        ),
    ]
