# Generated by Django 3.2.18 on 2023-07-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20230716_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='first_image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='second_image',
            new_name='image2',
        ),
    ]
