# Generated by Django 3.2.18 on 2023-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20230716_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='image1',
            field=models.ImageField(upload_to='events_images/'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='image2',
            field=models.ImageField(upload_to='events_images/'),
        ),
    ]
