# Generated by Django 3.2.18 on 2023-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='image1',
            field=models.ImageField(upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='image2',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
