# Generated by Django 3.2.18 on 2023-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hot_deal_images/')),
                ('title', models.CharField(max_length=100)),
                ('discount', models.PositiveIntegerField()),
                ('offer_end_period', models.DateField()),
                ('instruction', models.TextField()),
            ],
        ),
    ]
