# Generated by Django 4.2.3 on 2023-07-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0019_auto_20230417_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bar_menu_listed',
            field=models.CharField(default='This is the bar menu listed below to fill up', max_length=100),
        ),
    ]
