# Generated by Django 3.2.18 on 2023-07-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0021_offersection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersection',
            old_name='pattern_image',
            new_name='offer_image',
        ),
    ]
