# Generated by Django 3.2.18 on 2023-07-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0022_rename_pattern_image_offersection_offer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='offersection',
            name='text',
        ),
    ]
