# Generated by Django 3.2.18 on 2023-07-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0023_auto_20230713_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersection',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='offersection',
            name='offer_image',
        ),
        migrations.AddField(
            model_name='offersection',
            name='image',
            field=models.ImageField(default='', upload_to='offer_images/'),
            preserve_default=False,
        ),
    ]
