# Generated by Django 3.2.18 on 2023-07-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0026_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='title',
        ),
    ]
