# Generated by Django 3.2.18 on 2023-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0027_auto_20230714_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=100)),
            ],
        ),
    ]
