# Generated by Django 3.2.18 on 2023-07-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0029_auto_20230716_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
