# Generated by Django 3.2.18 on 2023-07-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0030_delete_aboutsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
