# Generated by Django 4.2.3 on 2023-07-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0038_alter_item_dish_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCount',
        ),
    ]
